import { compile } from "json-schema-to-typescript";
import type { EntityDefinition } from "./schema.js";

const HEADER_NODE = `// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types
//
// Setup: Add to tsconfig.json:
//   { "include": ["src", "base44/types.d.ts"] }
`;

const HEADER_DENO = `// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types
//
// Setup: Add to deno.json:
//   { "compilerOptions": { "types": ["./base44/types.deno.d.ts"] } }
//
// Or add to your entry file:
//   /// <reference path="./base44/types.deno.d.ts" />
`;

/** Options for json-schema-to-typescript */
const COMPILE_OPTIONS = {
  bannerComment: "",
  additionalProperties: false,
  strictIndexSignatures: true,
  enableConstEnums: true,
  declareExternallyReferenced: false,
};

/**
 * Generate TypeScript interface from JSON Schema
 */
async function generateEntityInterface(entity: EntityDefinition): Promise<string> {
  const schema = {
    ...entity,
    title: entity.name,
    $schema: "http://json-schema.org/draft-07/schema#",
  };

  return await compile(schema, entity.name, COMPILE_OPTIONS);
}

/**
 * Generate all entity interfaces
 */
async function generateEntityInterfaces(entities: EntityDefinition[]): Promise<string> {
  const interfaces = await Promise.all(entities.map(generateEntityInterface));
  return interfaces.join("\n");
}

/**
 * Generate the module augmentation block
 */
function generateModuleAugmentation(
  entities: EntityDefinition[],
  moduleName: string
): string {
  if (entities.length === 0) {
    return "";
  }

  const registryEntries = entities
    .map((e) => `    ${e.name}: ${e.name};`)
    .join("\n");

  return `
// ─── SDK Type Augmentation ───────────────────────────────────────

declare module '${moduleName}' {
  interface EntityTypeRegistry {
${registryEntries}
  }
}
`;
}

/**
 * Generate types.d.ts for Node.js
 * Uses: declare module '@base44/sdk'
 */
export async function generateNodeTypes(entities: EntityDefinition[]): Promise<string> {
  const entityInterfaces = await generateEntityInterfaces(entities);
  const moduleAugmentation = generateModuleAugmentation(entities, "@base44/sdk");

  return `${HEADER_NODE}
// ─── Entity Types ────────────────────────────────────────────────

${entityInterfaces}
${moduleAugmentation}`;
}

/**
 * Generate types.deno.d.ts for Deno
 * Uses: declare module 'npm:@base44/sdk'
 */
export async function generateDenoTypes(entities: EntityDefinition[]): Promise<string> {
  const entityInterfaces = await generateEntityInterfaces(entities);
  const moduleAugmentation = generateModuleAugmentation(entities, "npm:@base44/sdk");

  return `${HEADER_DENO}
// ─── Entity Types ────────────────────────────────────────────────

${entityInterfaces}
${moduleAugmentation}`;
}
