import type { EntityDefinition, EntityField } from "./schema.js";

const HEADER = `// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types
`;

/**
 * Convert a JSON Schema type to TypeScript type
 */
function fieldToTypeScript(field: EntityField, required: boolean): string {
  let tsType: string;

  // Handle enums
  if (field.enum && field.enum.length > 0) {
    tsType = field.enum.map((v) => `'${v}'`).join(" | ");
  } else {
    switch (field.type) {
      case "string":
        tsType = "string";
        break;
      case "number":
        tsType = "number";
        break;
      case "boolean":
        tsType = "boolean";
        break;
      case "array":
        if (field.items) {
          const itemType = fieldToTypeScript(field.items, true);
          tsType = `${itemType}[]`;
        } else {
          tsType = "unknown[]";
        }
        break;
      case "object":
        if (field.properties) {
          const props = Object.entries(field.properties)
            .map(([name, prop]) => {
              const isRequired = field.required?.includes(name) ?? false;
              const propType = fieldToTypeScript(prop, isRequired);
              return `${name}${isRequired ? "" : "?"}: ${propType}`;
            })
            .join("; ");
          tsType = `{ ${props} }`;
        } else {
          tsType = "Record<string, unknown>";
        }
        break;
      default:
        tsType = "unknown";
    }
  }

  return tsType;
}

/**
 * Generate interface fields for an entity
 */
function generateInterfaceFields(
  entity: EntityDefinition,
  options: { allOptional?: boolean } = {}
): string {
  if (!entity.properties) {
    return "";
  }

  const requiredFields = new Set(entity.required ?? []);

  return Object.entries(entity.properties)
    .map(([fieldName, field]) => {
      const isRequired = options.allOptional
        ? false
        : requiredFields.has(fieldName);
      const tsType = fieldToTypeScript(field, isRequired);
      const optional = isRequired ? "" : "?";
      const description = field.description
        ? `  /** ${field.description} */\n`
        : "";
      return `${description}  ${fieldName}${optional}: ${tsType};`;
    })
    .join("\n");
}

/**
 * Generate TypeScript interfaces for a single entity
 */
function generateEntityTypes(entity: EntityDefinition): string {
  const name = entity.name;
  const fields = generateInterfaceFields(entity);
  const createFields = generateInterfaceFields(entity);
  const updateFields = generateInterfaceFields(entity, { allOptional: true });
  const filterFields = generateInterfaceFields(entity, { allOptional: true });

  return `
/** ${name} entity */
export interface ${name} extends BaseEntity {
${fields}
}

/** Input for creating a ${name} */
export interface ${name}CreateInput {
${createFields}
}

/** Input for updating a ${name} (all fields optional) */
export interface ${name}UpdateInput {
${updateFields}
}

/** Filter query for ${name} */
export interface ${name}Filter {
${filterFields}
}
`;
}

/**
 * Generate the entities.ts file content
 */
export function generateEntitiesFile(entities: EntityDefinition[]): string {
  const baseEntity = `
/** System fields present on all entities */
export interface BaseEntity {
  id: string;
  created_date: string;
  updated_date: string;
}
`;

  const entityTypes = entities.map(generateEntityTypes).join("\n");

  // Generate union type of all entity names
  const entityNames = entities.map((e) => `'${e.name}'`).join(" | ");
  const entityNamesType = entities.length > 0
    ? `\n/** All entity names in this project */\nexport type EntityName = ${entityNames};\n`
    : "";

  return HEADER + baseEntity + entityTypes + entityNamesType;
}

/**
 * Generate the client.ts file content with typed SDK wrapper
 */
export function generateClientFile(entities: EntityDefinition[]): string {
  if (entities.length === 0) {
    return HEADER + "\n// No entities found\nexport {};\n";
  }

  // Generate imports
  const imports = entities
    .map((e) => `${e.name}, ${e.name}CreateInput, ${e.name}UpdateInput, ${e.name}Filter`)
    .join(",\n  ");

  // Generate entity handlers
  const handlers = entities
    .map(
      (e) =>
        `  ${e.name}: EntityHandler<${e.name}, ${e.name}CreateInput, ${e.name}UpdateInput, ${e.name}Filter>;`
    )
    .join("\n");

  return `${HEADER}
import type {
  ${imports}
} from './entities.js';

/** Response for list/filter operations */
export interface ListResponse<T> {
  items: T[];
  total: number;
}

/** Real-time subscription event */
export interface RealtimeEvent<T> {
  type: 'create' | 'update' | 'delete';
  data: T;
  id: string;
  timestamp: string;
}

/** Entity handler with CRUD operations */
export interface EntityHandler<T, TCreate, TUpdate, TFilter> {
  /** Get all records with optional pagination */
  list(sort?: string, limit?: number, skip?: number, fields?: (keyof T)[]): Promise<ListResponse<T>>;
  /** Get records matching filter criteria */
  filter(query: TFilter, sort?: string, limit?: number, skip?: number, fields?: (keyof T)[]): Promise<ListResponse<T>>;
  /** Get a single record by ID */
  get(id: string): Promise<T>;
  /** Create a new record */
  create(data: TCreate): Promise<T>;
  /** Update an existing record */
  update(id: string, data: TUpdate): Promise<T>;
  /** Delete a record */
  delete(id: string): Promise<void>;
  /** Delete multiple records matching filter */
  deleteMany(query: TFilter): Promise<void>;
  /** Create multiple records at once */
  bulkCreate(data: TCreate[]): Promise<T[]>;
  /** Subscribe to real-time updates */
  subscribe(callback: (event: RealtimeEvent<T>) => void): () => void;
}

/** Typed entities interface for Base44 SDK */
export interface TypedEntities {
${handlers}
}

/**
 * Typed Base44 client interface.
 * Use with the Base44 SDK for type-safe entity access.
 *
 * @example
 * import { createClient } from '@base44/sdk';
 * import type { TypedBase44Client } from './base44/client';
 *
 * const base44 = createClient({ appId: 'your-app-id' }) as TypedBase44Client;
 * const tasks = await base44.entities.Task.list();
 */
export interface TypedBase44Client {
  entities: TypedEntities;
}
`;
}

/**
 * Generate the index.ts barrel file
 */
export function generateIndexFile(): string {
  return `${HEADER}
export * from './entities.js';
export * from './client.js';
`;
}
