import { source, stripIndent } from "common-tags";
import type { AgentConfig } from "@/core/resources/agent/index.js";
import type { Entity } from "@/core/resources/entity/index.js";
import type { BackendFunction } from "@/core/resources/function/index.js";
import {
  generateAgentRegistryEntries,
  generateAllEntityInterfaces,
  generateEntityRegistryEntries,
  generateFunctionRegistryEntries,
} from "./generator.js";

export interface TemplateInput {
  entities: Entity[];
  functions: BackendFunction[];
  agents: AgentConfig[];
}

const HEADER = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types
  //
  // Setup: Add to tsconfig.json:
  //   { "include": ["src", "base44/.types"] }
`;

const EMPTY_TEMPLATE = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types
  //
  // No entities, functions, or agents found in project.
  // Add resources to base44/entities/, base44/functions/, or base44/agents/
  // and run \`base44 types\` again.

  declare module '@base44/sdk' {
    // No types to augment - add resources and regenerate
  }
`;

function registryInterface(name: string, entries: string): string {
  return source`
    interface ${name} {
    ${entries}
    }
  `;
}

export async function generateTypesFileContent(
  input: TemplateInput
): Promise<string> {
  const { entities, functions, agents } = input;

  if (!entities.length && !functions.length && !agents.length) {
    return EMPTY_TEMPLATE;
  }

  // Build registries for each resource type that has items
  const registryConfigs: [string, string][] = [
    ["EntityTypeRegistry", generateEntityRegistryEntries(entities)],
    ["FunctionNameRegistry", generateFunctionRegistryEntries(functions)],
    ["AgentNameRegistry", generateAgentRegistryEntries(agents)],
  ];

  const registries = registryConfigs
    .filter(([, entries]) => entries)
    .map(([name, entries]) => registryInterface(name, entries));

  const entityInterfaces = await generateAllEntityInterfaces(entities);

  return [
    HEADER,
    entityInterfaces,
    source`
      declare module '@base44/sdk' {
        ${registries.join("\n\n")}
      }
    `,
  ]
    .filter(Boolean)
    .join("\n\n");
}
