import type { Entity } from "@/core/resources/entity/index.js";
import type { Function } from "@/core/resources/function/index.js";
import type { AgentConfig } from "@/core/resources/agent/index.js";
import {
  generateAllEntityInterfaces,
  generateEntityRegistryEntries,
  generateFunctionRegistryEntries,
  generateAgentRegistryEntries,
} from "./generator.js";

/**
 * Input for generating the types file.
 */
export interface TemplateInput {
  entities: Entity[];
  functions: Function[];
  agents: AgentConfig[];
}

/**
 * Generate the complete types.d.ts file content.
 */
export async function generateTypesFileContent(input: TemplateInput): Promise<string> {
  const { entities, functions, agents } = input;

  // Generate entity interfaces
  const entityInterfaces = await generateAllEntityInterfaces(entities);

  // Generate registry entries
  const entityRegistryEntries = generateEntityRegistryEntries(entities);
  const functionRegistryEntries = generateFunctionRegistryEntries(functions);
  const agentRegistryEntries = generateAgentRegistryEntries(agents);

  // Check if we have any content to generate
  const hasEntities = entities.length > 0;
  const hasFunctions = functions.length > 0;
  const hasAgents = agents.length > 0;

  if (!hasEntities && !hasFunctions && !hasAgents) {
    return generateEmptyTypesFile();
  }

  const sections: string[] = [];

  // Header
  sections.push(`// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types
//
// Setup: Add to tsconfig.json:
//   { "include": ["src", "base44/types.d.ts"] }`);

  // Entity interfaces section
  if (hasEntities) {
    sections.push(`
// ─── Entity Types ────────────────────────────────────────────────

${entityInterfaces}`);
  }

  // SDK Type Augmentation section
  sections.push(`
// ─── SDK Type Augmentation ───────────────────────────────────────

declare module '@base44/sdk' {`);

  // Entity registry
  if (hasEntities) {
    sections.push(`  interface EntityTypeRegistry {
${entityRegistryEntries}
  }`);
  }

  // Function registry
  if (hasFunctions) {
    sections.push(`
  interface FunctionNameRegistry {
${functionRegistryEntries}
  }`);
  }

  // Agent registry
  if (hasAgents) {
    sections.push(`
  interface AgentNameRegistry {
${agentRegistryEntries}
  }`);
  }

  sections.push(`}`);

  return sections.join("\n");
}

/**
 * Generate an empty types file when no resources exist.
 */
function generateEmptyTypesFile(): string {
  return `// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types
//
// No entities, functions, or agents found in project.
// Add resources to base44/entities/, base44/functions/, or base44/agents/
// and run \`base44 types\` again.

declare module '@base44/sdk' {
  // No types to augment - add resources and regenerate
}
`;
}
