import { source, stripIndent } from "common-tags";
import type { JSONSchema4 } from "json-schema";
import { compile } from "json-schema-to-typescript";
import { getTypesOutputPath } from "@/core/config.js";
import { TypeGenerationError } from "@/core/errors.js";
import type { AgentConfig } from "@/core/resources/agent/index.js";
import type { ConnectorResource } from "@/core/resources/connector/index.js";
import type { Entity } from "@/core/resources/entity/index.js";
import type { BackendFunction } from "@/core/resources/function/index.js";
import type { RealtimeHandler } from "@/core/resources/realtime-handler/schema.js";
import { writeFile } from "@/core/utils/fs.js";

interface GenerateTypesInput {
  projectRoot: string;
  entities: Entity[];
  functions: BackendFunction[];
  agents: AgentConfig[];
  connectors: ConnectorResource[];
  realtimeHandlers: RealtimeHandler[];
}

const HEADER = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types generate
`;

const EMPTY_TEMPLATE = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types
  //
  // No entities, functions, agents, connectors, or realtime handlers found in project.
  // Add resources to base44/entities/, base44/functions/, base44/agents/, base44/connectors/, or base44/realtime/
  // and run \`base44 types generate\` again.

  declare module '@base44/sdk' {
    // No types to augment - add resources and regenerate
  }
`;

/**
 * Generate and write types.d.ts file.
 */
export async function generateTypesFile(
  input: GenerateTypesInput,
): Promise<void> {
  const content = await generateContent(input);
  await writeFile(getTypesOutputPath(input.projectRoot), content);
}

async function generateContent(input: GenerateTypesInput): Promise<string> {
  const { entities, functions, agents, connectors, realtimeHandlers } = input;

  if (
    !entities.length &&
    !functions.length &&
    !agents.length &&
    !connectors.length &&
    !realtimeHandlers.length
  ) {
    return EMPTY_TEMPLATE;
  }

  const [entityInterfaces, realtimeRegistryEntries] = await Promise.all([
    Promise.all(entities.map((e) => compileEntity(e))),
    Promise.all(realtimeHandlers.map((h) => compileRealtimeHandler(h))),
  ]);

  // Build registry entries
  const registryEntries: [string, string[]][] = [
    [
      "EntityTypeRegistry",
      entities.map((e) => `"${e.name}": ${toPascalCase(e.name)};`),
    ],
    ["FunctionNameRegistry", functions.map((f) => `"${f.name}": true;`)],
    ["AgentNameRegistry", agents.map((a) => `"${a.name}": true;`)],
    ["ConnectorTypeRegistry", connectors.map((c) => `"${c.type}": true;`)],
    [
      "RealtimeHandlerNameRegistry",
      realtimeHandlers.map((h) => `"${h.name}": true;`),
    ],
    [
      "RealtimeHandlerRegistry",
      realtimeHandlers
        .filter((h) => h.messageSchema)
        .map((h, _, arr) => {
          const idx = realtimeHandlers.indexOf(h);
          return `"${h.name}": ${realtimeRegistryEntries[idx]};`;
        }),
    ],
  ];

  // Generate registries (only for non-empty entries)
  const registries = registryEntries
    .filter(([, entries]) => entries.length > 0)
    .map(([name, entries]) => registry(name, entries));

  return [
    HEADER,
    entityInterfaces.join("\n\n"),
    source`
      declare module '@base44/sdk' {
        ${registries.join("\n\n")}
      }
    `,
  ]
    .filter(Boolean)
    .join("\n\n");
}

async function compileEntity(entity: Entity): Promise<string> {
  const { name, source: _source, ...schema } = entity;

  const jsonSchema = {
    ...schema,
    title: name,
    additionalProperties: false,
  } as JSONSchema4;

  try {
    const ts = await compile(jsonSchema, name, {
      bannerComment: "",
      additionalProperties: false,
      strictIndexSignatures: true,
    });
    return ts.trim();
  } catch (error) {
    throw new TypeGenerationError(
      `Failed to generate types for entity "${name}"`,
      name,
      error,
    );
  }
}

async function compileRealtimeHandler(handler: RealtimeHandler): Promise<string> {
  const { messageSchema } = handler;
  if (!messageSchema) return "{ inbound: unknown; outbound: unknown }";

  const compileSchema = async (schema: Record<string, unknown> | undefined, typeName: string): Promise<string> => {
    if (!schema) return "unknown";
    try {
      const ts = await compile(schema as JSONSchema4, typeName, {
        bannerComment: "",
        additionalProperties: false,
        strictIndexSignatures: true,
      });
      // extract just the interface body, not the full `interface X { ... }` declaration
      const match = ts.match(/\{([^]*)\}/);
      return match ? `{\n${match[1]}}` : "unknown";
    } catch {
      return "unknown";
    }
  };

  const [inbound, outbound] = await Promise.all([
    compileSchema(messageSchema.inbound as Record<string, unknown> | undefined, `${handler.name}Inbound`),
    compileSchema(messageSchema.outbound as Record<string, unknown> | undefined, `${handler.name}Outbound`),
  ]);

  return `{ inbound: ${inbound}; outbound: ${outbound} }`;
}

function registry(name: string, entries: string[]): string {
  return source`
    interface ${name} {
      ${entries.join("\n")}
    }
  `;
}

function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}
