import { join } from "node:path";
import { source, stripIndent } from "common-tags";
import type { JSONSchema4 } from "json-schema";
import { compile } from "json-schema-to-typescript";
import { getTypesOutputPath } from "@/core/config.js";
import { TypeGenerationError } from "@/core/errors.js";
import type { AgentConfig } from "@/core/resources/agent/index.js";
import type { ConnectorResource } from "@/core/resources/connector/index.js";
import type { Entity } from "@/core/resources/entity/index.js";
import type { BackendFunction } from "@/core/resources/function/index.js";
import type { RealtimeHandler } from "@/core/resources/realtime-handler/schema.js";
import { readJsonFile, writeFile } from "@/core/utils/fs.js";

interface GenerateTypesInput {
  projectRoot: string;
  entities: Entity[];
  functions: BackendFunction[];
  agents: AgentConfig[];
  connectors: ConnectorResource[];
  realtimeHandlers: RealtimeHandler[];
}

const HEADER = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types generate
`;

const EMPTY_TEMPLATE = stripIndent`
  // Auto-generated by Base44 CLI - DO NOT EDIT
  // Regenerate with: base44 types
  //
  // No entities, functions, agents, connectors, or realtime handlers found in project.
  // Add resources to base44/entities/, base44/functions/, base44/agents/, base44/connectors/, or base44/realtime/
  // and run \`base44 types generate\` again.

  declare module '@base44/sdk' {
    // No types to augment - add resources and regenerate
  }
`;

const SDK_PACKAGE_NAMES = ["@base44/sdk", "@base44-preview/sdk"] as const;
type SdkPackageName = (typeof SDK_PACKAGE_NAMES)[number];

async function detectSdkPackageName(
  projectRoot: string,
): Promise<SdkPackageName> {
  try {
    const pkg = (await readJsonFile(
      join(projectRoot, "package.json"),
    )) as Record<string, unknown>;
    const deps = {
      ...(pkg.dependencies as object),
      ...(pkg.devDependencies as object),
    };
    for (const name of SDK_PACKAGE_NAMES) {
      if (name in deps) return name;
    }
  } catch {
    // ignore
  }
  return "@base44/sdk";
}

/**
 * Generate and write types.d.ts file.
 */
export async function generateTypesFile(
  input: GenerateTypesInput,
): Promise<void> {
  const content = await generateContent(input);
  await writeFile(getTypesOutputPath(input.projectRoot), content);
}

export async function generateContent(
  input: GenerateTypesInput,
): Promise<string> {
  const { entities, functions, agents, connectors, realtimeHandlers } = input;
  const sdkPackage = await detectSdkPackageName(input.projectRoot);

  if (
    !entities.length &&
    !functions.length &&
    !agents.length &&
    !connectors.length &&
    !realtimeHandlers.length
  ) {
    return EMPTY_TEMPLATE;
  }

  const [entityInterfaces, realtimeResults] = await Promise.all([
    Promise.all(entities.map((e) => compileEntity(e))),
    Promise.all(realtimeHandlers.map((h) => compileRealtimeHandler(h))),
  ]);

  // Build registry entries
  const registryEntries: [string, string[]][] = [
    [
      "EntityTypeRegistry",
      entities.map((e) => `"${e.name}": ${toPascalCase(e.name)};`),
    ],
    ["FunctionNameRegistry", functions.map((f) => `"${f.name}": true;`)],
    ["AgentNameRegistry", agents.map((a) => `"${a.name}": true;`)],
    ["ConnectorTypeRegistry", connectors.map((c) => `"${c.type}": true;`)],
    [
      "RealtimeHandlerNameRegistry",
      realtimeHandlers.map((h) => `"${h.name}": true;`),
    ],
    [
      "RealtimeHandlerRegistry",
      realtimeHandlers
        .filter((h) => h.messageSchema)
        .map((h) => {
          const idx = realtimeHandlers.indexOf(h);
          return `"${h.name}": ${realtimeResults[idx].entry};`;
        }),
    ],
  ];

  // Generate registries (only for non-empty entries)
  const registries = registryEntries
    .filter(([, entries]) => entries.length > 0)
    .map(([name, entries]) => registry(name, entries));

  const realtimeInterfaces = realtimeResults
    .map((r) => r.decls)
    .filter(Boolean);

  return [
    HEADER,
    "export {};", // module context — ensures declare module augments rather than replaces the SDK package
    entityInterfaces.join("\n\n"),
    realtimeInterfaces.join("\n\n"),
    source`
      declare module '${sdkPackage}' {
        ${registries.join("\n\n")}
      }
    `,
  ]
    .filter(Boolean)
    .join("\n\n");
}

async function compileEntity(entity: Entity): Promise<string> {
  const { name, source: _source, ...schema } = entity;

  const jsonSchema = {
    ...schema,
    title: name,
    additionalProperties: false,
  } as JSONSchema4;

  try {
    const ts = await compile(jsonSchema, name, {
      bannerComment: "",
      additionalProperties: false,
      strictIndexSignatures: true,
    });
    return ts.trim();
  } catch (error) {
    throw new TypeGenerationError(
      `Failed to generate types for entity "${name}"`,
      name,
      error,
    );
  }
}

interface RealtimeCompileResult {
  /** Top-level `export` declarations: one interface per message + shared types. */
  decls: string;
  /** The registry value, e.g. `{ inbound: FooInit | FooTick; outbound: FooJoin }`. */
  entry: string;
}

/**
 * A handler's `schema.jsonc` is a *catalog* of named messages:
 *   { types?: { Pt, Snake, … }, inbound: { init, tick, … }, outbound: { join, … } }
 * Each message is a flat object schema (no `type` field — the generator injects
 * `type: "<name>"` as the discriminant). We compile the whole catalog in ONE pass
 * so json-schema-to-typescript emits a named interface per message plus the shared
 * types, then assemble the inbound/outbound unions from those names. This avoids
 * scraping the compiler output (the old regex broke on unions and `$defs`), and
 * because every message is a single flat object, the fragile multi-declaration
 * case never arises.
 */
async function compileRealtimeHandler(
  handler: RealtimeHandler,
): Promise<RealtimeCompileResult> {
  const { messageSchema } = handler;
  if (!messageSchema) {
    return { decls: "", entry: "{ inbound: unknown; outbound: unknown }" };
  }

  const prefix = toPascalCase(handler.name);
  const types = (messageSchema.types ?? {}) as Record<string, JSONSchema4>;
  const inbound = (messageSchema.inbound ?? {}) as Record<string, JSONSchema4>;
  const outbound = (messageSchema.outbound ?? {}) as Record<string, JSONSchema4>;

  // Shared types are prefixed with the handler name so names (Pt, Snake, …) can't
  // collide across handlers or with entity interfaces. Messages additionally carry
  // their direction, since the same name (e.g. "message") may appear both inbound
  // and outbound.
  const typeName = (key: string) => `${prefix}${toPascalCase(key)}`;
  const msgName = (dir: "Inbound" | "Outbound", key: string) =>
    `${prefix}${dir}${toPascalCase(key)}`;

  const defs: Record<string, JSONSchema4> = {};
  const add = (name: string, schema: JSONSchema4) => {
    if (name in defs) {
      throw new TypeGenerationError(
        `Duplicate generated type "${name}" in realtime handler "${handler.name}" — a shared type and a message resolve to the same name.`,
        handler.name,
      );
    }
    defs[name] = { ...schema, title: name };
  };

  // Shared types are emitted as-is (author writes `type: "object"` etc.); their
  // author-facing `#/types/X` refs are rewritten to the prefixed `#/$defs/` names.
  for (const [key, schema] of Object.entries(types)) {
    add(typeName(key), rewriteTypeRefs(schema, typeName) as JSONSchema4);
  }

  // Each message → one flat object (a full JSON Schema, like an entity) with the
  // `type` discriminant injected from its key.
  const compileMessages = (
    msgs: Record<string, JSONSchema4>,
    dir: "Inbound" | "Outbound",
  ): string[] =>
    Object.entries(msgs).map(([key, schema]) => {
      const name = msgName(dir, key);
      const rewritten = rewriteTypeRefs(schema, typeName) as JSONSchema4;
      add(name, {
        type: "object",
        ...rewritten,
        properties: { type: { const: key }, ...(rewritten.properties ?? {}) },
        required: ["type", ...((rewritten.required as string[] | undefined) ?? [])],
        additionalProperties: false,
      });
      return name;
    });

  const inboundNames = compileMessages(inbound, "Inbound");
  const outboundNames = compileMessages(outbound, "Outbound");

  // Root union over every message keeps all defs reachable so the compiler emits
  // them; we keep its whole output verbatim (no scraping).
  const allNames = [...inboundNames, ...outboundNames];
  const rootName = `${prefix}Message`;
  const rootSchema = {
    title: rootName,
    $defs: defs,
    oneOf: allNames.map((n) => ({ $ref: `#/$defs/${n}` })),
  } as unknown as JSONSchema4;

  let decls = "";
  try {
    decls = (
      await compile(rootSchema, rootName, {
        bannerComment: "",
        additionalProperties: false,
        strictIndexSignatures: true,
      })
    ).trim();
  } catch (error) {
    throw new TypeGenerationError(
      `Failed to generate types for realtime handler "${handler.name}"`,
      handler.name,
      error,
    );
  }

  const union = (names: string[]) => (names.length ? names.join(" | ") : "never");
  return {
    decls,
    entry: `{ inbound: ${union(inboundNames)}; outbound: ${union(outboundNames)} }`,
  };
}

/** Rewrite author-facing `#/types/X` refs to the prefixed `#/$defs/<defName>`. */
function rewriteTypeRefs(
  node: unknown,
  defName: (key: string) => string,
): unknown {
  if (Array.isArray(node)) {
    return node.map((n) => rewriteTypeRefs(n, defName));
  }
  if (node && typeof node === "object") {
    const out: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(node)) {
      const match =
        key === "$ref" && typeof value === "string"
          ? value.match(/^#\/types\/(.+)$/)
          : null;
      out[key] = match
        ? `#/$defs/${defName(match[1])}`
        : rewriteTypeRefs(value, defName);
    }
    return out;
  }
  return node;
}

function registry(name: string, entries: string[]): string {
  return source`
    interface ${name} {
      ${entries.join("\n")}
    }
  `;
}

function toPascalCase(name: string): string {
  return name
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
}
