// Generates dist/deno-shim.mjs, dist/activation-shim.mjs, and dist/actor.mjs
// (the injected shims, build artifacts — not committed). Re-run after changing
// entry.ts / activation.ts / actor.ts or bumping @deno/shim-deno.

import { fileURLToPath } from "node:url";

import { build, type BuildOptions } from "esbuild";

import { nodeBuiltinRequirePlugin } from "../src/esbuild/node-builtin-require.js";
import { RUNTIME_CONTEXT_SPECIFIER } from "../src/esbuild/runtime-context-virtual.js";

const resolve = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));

const shared: BuildOptions = {
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "node",
  mainFields: ["module", "main"],
  conditions: ["import", "node"],
  // Keep the internal manifest-store + runtime-context imports external here so
  // they survive into the dist shims as bare specifiers; the FINAL app compile's
  // virtual plugins resolve them (the manifest store deduped with manifest.ts to
  // a single module instance — see runtime-manifest-store).
  external: [
    "cloudflare:workers",
    "base44:private-data-sources/runtime-manifest-store",
    RUNTIME_CONTEXT_SPECIFIER,
  ],
  treeShaking: true,
  minify: false,
  legalComments: "none",
  plugins: [nodeBuiltinRequirePlugin()],
};

await build({
  ...shared,
  entryPoints: [resolve("../src/shim/entry.ts")],
  outfile: resolve("../dist/deno-shim.mjs"),
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/entry.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

await build({
  ...shared,
  entryPoints: [resolve("../src/shim/activation.ts")],
  outfile: resolve("../dist/activation-shim.mjs"),
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/activation.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

// Actor shim targets CF Workers (browser-like, no Node.js APIs).
await build({
  entryPoints: [resolve("../src/shim/actor.ts")],
  outfile: resolve("../dist/actor.mjs"),
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "browser",
  // Any @base44/sdk version stays external — the Deno resolver bundles it at
  // user-function-bundle time. Version-agnostic so this list never needs a bump;
  // the actual version is the pin on the shim's own import in src/shim/actor.ts.
  external: ["cloudflare:workers", "npm:@base44/sdk*"],
  treeShaking: true,
  minify: false,
  legalComments: "none",
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/actor.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

console.log("built dist/deno-shim.mjs + dist/activation-shim.mjs + dist/actor.mjs");
