// Generates src/generated/assets.ts: the three injected shims (built here from
// src/shim/) and the .ts modules the esbuild plugins serve as text, embedded as
// strings so the compiler reads no file of its own and survives being bundled.
// A build artifact, not committed; `prepare` runs it on install. Re-run after
// changing a shim, a runtime module or a private data source, or bumping
// @deno/shim-deno.

import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { build, type BuildOptions } from "esbuild";

import { nodeBuiltinRequirePlugin } from "../src/esbuild/node-builtin-require.js";
import { RUNTIME_CONTEXT_SPECIFIER } from "../src/esbuild/runtime-context-specifier.js";

const resolve = (rel: string) => fileURLToPath(new URL(rel, import.meta.url));

/** Built in memory: the only copy is the embedded one. Each build still names
 *  an `outfile` — esbuild writes source paths relative to it into the shim's
 *  comments, and those bytes reach every compiled Worker. */
async function shim(options: BuildOptions): Promise<string> {
  const result = await build({ ...options, write: false });
  return result.outputFiles![0].text;
}

const shared: BuildOptions = {
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "node",
  mainFields: ["module", "main"],
  conditions: ["import", "node"],
  // Keep the internal manifest-store + runtime-context imports external here so
  // they survive into the dist shims as bare specifiers; the FINAL app compile's
  // virtual plugins resolve them (the manifest store deduped with manifest.ts to
  // a single module instance — see runtime-manifest-store).
  external: [
    "cloudflare:workers",
    "base44:private-data-sources/runtime-manifest-store",
    RUNTIME_CONTEXT_SPECIFIER,
  ],
  treeShaking: true,
  minify: false,
  legalComments: "none",
  plugins: [nodeBuiltinRequirePlugin()],
};

const denoShim = await shim({
  ...shared,
  entryPoints: [resolve("../src/shim/entry.ts")],
  outfile: resolve("../dist/deno-shim.mjs"),
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/entry.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

const activationShim = await shim({
  ...shared,
  entryPoints: [resolve("../src/shim/activation.ts")],
  outfile: resolve("../dist/activation-shim.mjs"),
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/activation.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

// Actor shim targets CF Workers (browser-like, no Node.js APIs).
const actorShim = await shim({
  entryPoints: [resolve("../src/shim/actor.ts")],
  outfile: resolve("../dist/actor.mjs"),
  bundle: true,
  format: "esm",
  target: "es2022",
  platform: "browser",
  // Any @base44/sdk version stays external — the Deno resolver bundles it at
  // user-function-bundle time. Version-agnostic so this list never needs a bump;
  // the actual version is the pin on the shim's own import in src/shim/actor.ts.
  external: ["cloudflare:workers", "npm:@base44/sdk*"],
  treeShaking: true,
  minify: false,
  legalComments: "none",
  banner: {
    js: "// GENERATED by scripts/build-shim.ts from src/shim/actor.ts — do not edit.\n// Regenerate with `npm run build:shim`.",
  },
});

// Read as TEXT by the esbuild plugins and handed to esbuild with a "ts" loader;
// they must stay TypeScript, so tsc never compiles them.
const text = (rel: string) => readFile(resolve(`../src/${rel}`), "utf8");
const dataSources = (await readdir(resolve("../src/private-data-sources")))
  .filter((name) => name.endsWith(".ts"))
  .sort();

const assets: Record<string, string> = {
  "deno-shim.mjs": denoShim,
  "activation-shim.mjs": activationShim,
  "actor.mjs": actorShim,
  "runtime/index.ts": await text("runtime/index.ts"),
  "runtime-context.ts": await text("runtime-context.ts"),
};
for (const name of dataSources) {
  assets[`private-data-sources/${name}`] = await text(`private-data-sources/${name}`);
}

await mkdir(resolve("../src/generated"), { recursive: true });
await writeFile(
  resolve("../src/generated/assets.ts"),
  [
    "// GENERATED by scripts/build-shim.ts — do not edit. Regenerate with `bun run build:shim`.",
    "export const ASSETS: Readonly<Record<string, string>> = {",
    ...Object.entries(assets).map(
      ([name, content]) => `  ${JSON.stringify(name)}: ${JSON.stringify(content)},`,
    ),
    "};",
    "",
  ].join("\n"),
);

console.log(`embedded ${Object.keys(assets).length} assets into src/generated/assets.ts`);
